[package]
name = "discord-bot"
version = "0.1.0"
authors = ["TheDoctorsLife <thedoctorslife@users.noreply.github.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
serde = "*"
serde_json = "*"
